import { FormEvent, useEffect, useState } from 'react';
import { deleteQuestionCategory, getQuestionCategories, QuestionCategory, saveQuestionCategory } from './api';

export function QuestionCategoryAdminPage({ token }: { token: string }) {
  const [categories, setCategories] = useState<QuestionCategory[]>([]); const [editingId, setEditingId] = useState<string>(); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [displayOrder, setDisplayOrder] = useState(0); const [active, setActive] = useState(true); const [filter, setFilter] = useState(''); const [error, setError] = useState('');
  async function load(): Promise<void> { setCategories((await getQuestionCategories(token)).data); }
  useEffect(() => { void load().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load question categories.')); }, [token]);
  function reset(): void { setEditingId(undefined); setName(''); setDescription(''); setDisplayOrder(0); setActive(true); }
  function edit(category: QuestionCategory): void { setEditingId(category.id); setName(category.name); setDescription(category.description ?? ''); setDisplayOrder(category.displayOrder); setActive(category.active); }
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); setError(''); try { await saveQuestionCategory(token, { name, description, displayOrder, active }, editingId); reset(); await load(); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Could not save question category.'); } }
  async function remove(category: QuestionCategory): Promise<void> { const affected = category._count?.questions ?? 0; let replacementCategoryId: string | undefined; if (affected) { replacementCategoryId = window.prompt(`${affected} question${affected === 1 ? '' : 's'} use ${category.name}. Enter the ID of an active replacement category.`, '') || undefined; if (!replacementCategoryId) return; } if (!window.confirm(`Remove ${category.name}${affected ? ` and reassign ${affected} question${affected === 1 ? '' : 's'}` : ''}?`)) return; try { await deleteQuestionCategory(token, category.id, replacementCategoryId); await load(); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Could not remove question category.'); } }
  const visible = categories.filter((category) => `${category.name} ${category.description ?? ''}`.toLowerCase().includes(filter.toLowerCase()));
  return <section><div className="section-heading"><div><h2>Question categories</h2><p>Manage ordered categories used by questions and assessments.</p></div><button type="button" onClick={reset}>New category</button></div>{error && <p className="error">{error}</p>}<form className="panel form-grid compact-form" onSubmit={submit}><h3>{editingId ? 'Edit category' : 'Create category'}</h3><label>Name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Display order<input type="number" min="0" value={displayOrder} onChange={(event) => setDisplayOrder(Number(event.target.value))} required /></label><label className="checkbox-label"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} /> Active</label><div><button type="submit">{editingId ? 'Save changes' : 'Create'}</button>{editingId && <button type="button" className="secondary" onClick={reset}>Cancel</button>}</div></form><label>Search categories<input value={filter} onChange={(event) => setFilter(event.target.value)} /></label><div className="table-wrap"><table><thead><tr><th>Order</th><th>Name</th><th>Description</th><th>Questions</th><th>Active</th><th>Actions</th></tr></thead><tbody>{visible.map((category) => <tr key={category.id}><td>{category.displayOrder}</td><td>{category.name}</td><td>{category.description}</td><td>{category._count?.questions ?? 0}</td><td>{category.active ? 'Yes' : 'No'}</td><td><button type="button" onClick={() => edit(category)}>Edit</button> <button type="button" className="danger" onClick={() => void remove(category)}>Remove</button></td></tr>)}</tbody></table></div></section>;
}
