import { FormEvent, useEffect, useState } from 'react';
import { deleteQuestionType, getQuestionTypes, QuestionType, saveQuestionType } from './api';

export function QuestionTypeAdminPage({ token }: { token: string }) {
  const [types, setTypes] = useState<QuestionType[]>([]); const [editingId, setEditingId] = useState<string>(); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [active, setActive] = useState(true); const [error, setError] = useState('');
  async function load(): Promise<void> { setTypes((await getQuestionTypes(token)).data); }
  useEffect(() => { void load().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load question types.')); }, [token]);
  function reset(): void { setEditingId(undefined); setName(''); setDescription(''); setActive(true); }
  function edit(type: QuestionType): void { setEditingId(type.id); setName(type.name); setDescription(type.description ?? ''); setActive(type.active); }
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); setError(''); try { await saveQuestionType(token, { name, description, active }, editingId); reset(); await load(); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Could not save question type.'); } }
  async function remove(type: QuestionType): Promise<void> { if (!window.confirm(`Delete ${type.name}?`)) return; try { await deleteQuestionType(token, type.id); await load(); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Could not delete question type.'); } }
  return <section><div className="section-heading"><div><h2>Question types</h2><p>Manage the categories available when creating questions.</p></div><button type="button" onClick={reset}>New question type</button></div>{error && <p className="error">{error}</p>}<form className="panel form-grid compact-form" onSubmit={submit}><h3>{editingId ? 'Edit question type' : 'Create question type'}</h3><label>Name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label className="checkbox-label"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} /> Active</label><div><button type="submit">{editingId ? 'Save changes' : 'Create'}</button>{editingId && <button type="button" className="secondary" onClick={reset}>Cancel</button>}</div></form><div className="table-wrap"><table><thead><tr><th>Name</th><th>Description</th><th>Active</th><th>Actions</th></tr></thead><tbody>{types.map((type) => <tr key={type.id}><td>{type.name}</td><td>{type.description}</td><td>{type.active ? 'Yes' : 'No'}</td><td><button type="button" onClick={() => edit(type)}>Edit</button> <button type="button" className="danger" onClick={() => void remove(type)}>Delete</button></td></tr>)}</tbody></table></div></section>;
}
